# Generated by Django 4.2.11 on 2025-03-20 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonial_remove_staff_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drillingrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='drillingrequest',
            name='requested_date',
        ),
        migrations.AddField(
            model_name='drillingrequest',
            name='depth_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drillingrequest',
            name='request_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='drillingrequest',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drillingrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
